# This workflow will do a clean install of node dependencies, build the source code

name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: git status
    - run: git branch -a
    - run: git fetch
    - run: git branch -a
    - run: git checkout --track -b release origin/release
    - run: 'git merge master -m "Action Release: Merging master to prepare release."'
    - run: npm ci
    - run: npm run build
    - run: mv dist docs
    - run: git add docs
    - run: 'git commit -m "Action Release: Updating docs with new build files to finish release."'
    - run: git status
